version: '3'
services:
  mysql_server:
    image: mysql:5.7
    container_name: ${CONTAINER_NAME}
    networks:
      - default-networking
    ports:
      - ${DATABASE_PORT}:3306
    expose:
      # Opens port 3306 on the container
      - ${DATABASE_PORT}
    volumes:
      - ${DATABASE_DIR}:/var/lib/mysql
      - ${DATABASE_DUMP}:/docker-entrypoint-initdb.d
      - ${DATABASE_SQL_DUMP}:/srv/sqldump
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DATABASE_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    restart: always
networks:
  default-networking:
    driver: bridge
